server:
  port: ${SERVER_PORT:8081}

spring:
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bookswap_auth}
    username: ${DB_USER:bookswap}
    password: ${DB_PASSWORD:bookswap}
  
  flyway:
    enabled: true
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bookswap_auth}
    user: ${DB_USER:bookswap}
    password: ${DB_PASSWORD:bookswap}
    locations: classpath:db/migration

# Gateway URL для OpenAPI server configuration
gateway:
  url: ${GATEWAY_URL:http://localhost:8080}

springdoc:
  api-docs:
    path: /v3/api-docs
    groups:
      enabled: true
    group-configs:
      - group: auth
        paths-to-match: /api/v1/**
  swagger-ui:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
