server:
  port: ${SERVER_PORT:8082}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bookswap_books}
    username: ${DB_USER:bookswap}
    password: ${DB_PASSWORD:bookswap}
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  
  flyway:
    enabled: true
    locations: classpath:db/migration

# Gateway URL для OpenAPI server configuration
gateway:
  url: ${GATEWAY_URL:http://localhost:8080}

springdoc:
  api-docs:
    path: /v3/api-docs
    groups:
      enabled: true
    group-configs:
      - group: book
        paths-to-match: /api/v1/**
  swagger-ui:
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    dev.petr: DEBUG
