server:
  port: ${SERVER_PORT:8080}

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**

        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/api/v1/books/**,/api/v1/genres/**

        - id: exchange-service
          uri: lb://exchange-service
          predicates:
            - Path=/api/v1/exchanges/**

        - id: publication-service
          uri: lb://publication-service
          predicates:
            - Path=/api/v1/publications/**,/api/v1/publishers/**

        - id: swagger-auth-service
          uri: lb://auth-service
          predicates:
            - Path=/v3/api-docs/auth
          filters:
            - RewritePath=/v3/api-docs/auth, /v3/api-docs
            # Переписываем server URLs на Gateway URL
            - ModifyResponseBody=String, String, #rewriteOpenApiServers

        - id: swagger-book-service
          uri: lb://book-service
          predicates:
            - Path=/v3/api-docs/book
          filters:
            - RewritePath=/v3/api-docs/book, /v3/api-docs
            - ModifyResponseBody=String, String, #rewriteOpenApiServers

        - id: swagger-exchange-service
          uri: lb://exchange-service
          predicates:
            - Path=/v3/api-docs/exchange
          filters:
            - RewritePath=/v3/api-docs/exchange, /v3/api-docs
            - ModifyResponseBody=String, String, #rewriteOpenApiServers

        - id: swagger-publication-service
          uri: lb://publication-service
          predicates:
            - Path=/v3/api-docs/publication
          filters:
            - RewritePath=/v3/api-docs/publication, /v3/api-docs
            - ModifyResponseBody=String, String, #rewriteOpenApiServers

      globalcors:
        corsConfigurations:
          '[/**]':
            # Используем allowedOriginPatterns для более гибкой настройки CORS
            # Разрешаем все origins для разработки (Swagger UI, разные порты)
            # В production следует указать конкретные домены
            allowedOriginPatterns: 
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
            exposedHeaders:
              - X-Total-Count
              - Content-Type
              - Authorization

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    # Настройка для использования Gateway URL вместо прямых URL сервисов
    use-root-path: false
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: Auth Service
        url: /v3/api-docs/auth
      - name: Book Service
        url: /v3/api-docs/book
      - name: Exchange Service
        url: /v3/api-docs/exchange
      - name: Publication Service
        url: /v3/api-docs/publication

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    dev.petr: DEBUG
    org.springframework.cloud.gateway: DEBUG
